[VIV-26041] Preference Learning
bixbydevelopers/capsule-sample-space-resorts pull request #14
Opened 2019-03-18 23:47 UTC by sarahmolinerroy

2019-03-25 22:54 UTC, jatinbviv requested changes
A few edits and changes requested.

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +a boolean of type `ViewAll` which is always true and is used as a proxy to
```suggestion
a boolean of type `ViewAll`, which is always true and is used as a proxy to
```

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +We train these to have the goal `SpaceResort#all` and we annotate any resort
```suggestion
We train these to have the goal `SpaceResort#all` and annotate any resort
```

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +signify that we want to display the full space resort, instead of focussing on a
```suggestion
signify that we want to display the full space resort, instead of focusing on a
```

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +Thus by definition the Selection Prompt for `SpaceResort` will definitely need
```suggestion
Accordingly, Selection Prompt for `SpaceResort` needs
```

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +We have now demonstrated two points.  Firstly, that the Selection Prompt
```suggestion
We have now demonstrated two points.  First, the Selection Prompt
```

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +We don't we set the goal to the `FindSpaceResorts` Action?
```suggestion
Why don't we set the goal to the `FindSpaceResorts` Action?
```

Do you mean this?

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +planets and search criteria as Values.  This will reissue a search with the new
```suggestion
planets and search criteria as Values.  This reissues a search with the new
```

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +Here the user is asking to know about a specific property of a space resort,
```suggestion
Here, the user is asking to know about a specific property of a space resort,
```

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +want to make some changes.  The goal remains `Order#commitOrder` and any Values
```suggestion
want to make some changes.  The goal remains `Order#commitOrder`, and any Values
```

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +do not contain a new input Value (ex: Change the number of astronauts), then we
```suggestion
do not contain a new input Value (ex: Change the number of astronauts), we
```

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +multiple candidates the user will be presented with a `SpaceResort` Selection
```suggestion
multiple candidates, the user will be presented with a `SpaceResort` Selection
```

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +the `SelectResort` Action.  This Action will take the hotels currently in
Make Action lowercase throughout.

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +`from-property` key. However, we elect to use the property projection approach
```suggestion
`from-property` key. However, we use the property projection approach
```

2019-03-25 22:54 UTC, jatinbviv commented on README.md
> +candidates in context, we have a Selection Prompt to ask the user to pick a
Lower case Selection Prompt throughout

2019-03-25 23:20 UTC, adanis reviewed
Some minor suggestions. For all the instances that have "Action", change it to "action" (we don't capitalize Action in the docs).

2019-03-25 23:20 UTC, adanis commented on README.md
> +use a match-pattern to then tie our views and dialogs for this property
We
use a match-pattern to then tie our views and dialogs for this property
projection to describe the whole hotel.

>

A match-pattern ties the views and dialogs for this property projection to describe the whole hotel

2019-03-25 23:20 UTC, adanis commented on README.md
> +Why do we treat this as a property projection instead of setting the goal to the
```suggestion
Why treat this as a property projection instead of setting the goal to the
```

2019-03-25 23:20 UTC, adanis commented on README.md
> +When the user wants to book a space resort and there were many possible
The tense in this sentence should be more consistent.

When the user wants to book a space resort and there are many possible candidates in context, the user picks a single one using a selection prompt, in order to continue with the booking (see SpaceResort Selection Prompt selection below for full details).

2019-03-25 23:20 UTC, adanis commented on README.md
> +flagged signal to the "find" queries because these should issue a new search via
should issue or would issue?

2019-03-25 23:20 UTC, adanis commented on README.md
> +We have now demonstrated two points.  Firstly, that the Selection Prompt
```suggestion
This example demonstrates two points.  First, that the Selection Prompt
```

2019-03-25 23:20 UTC, adanis commented on README.md
> +training must use `SpaceResort` as a goal. Secondly, that the "find" queries
```suggestion
training must use `SpaceResort` as a goal. Second, that the "find" queries
```

2019-03-25 23:20 UTC, adanis commented on README.md
> +outer "find" queries is `SpaceResort#all`, we annotate both the goal and the
```suggestion
outer "find" queries is `SpaceResort#all`, annotate both the goal and the
```

2019-03-25 23:20 UTC, adanis commented on README.md
> +"Continuation of" to also be `SpaceResort#all`.  We annotate any resort names,
```suggestion
"Continuation of" to also be `SpaceResort#all`.  Any resort names,
```

2019-03-25 23:20 UTC, adanis commented on README.md
> +planets and search criteria as Values.  This will reissue a search with the new
```suggestion
planets and search criteria are annotated as Values.  This reissues a search with the new
```

2019-03-25 23:20 UTC, adanis commented on README.md
> +"Continuation of" `SpaceResort`.  This allow pivoting between inner/outer "find"
```suggestion
"Continuation of" `SpaceResort`.  This allows pivoting between inner/outer "find"
```

2019-03-25 23:20 UTC, adanis commented on README.md
> +astronauts, etc.  All this will create a plan to first find a space resort that
```suggestion
astronauts, etc.  This creates a plan to first find a space resort that
```

2019-03-25 23:20 UTC, adanis commented on README.md
> +`CommitOrder` Action which will present the user with a Confirmation screen to
```suggestion
`CommitOrder` Action, which will present the user with a Confirmation screen to
```

2019-03-26 00:03 UTC, jatinbviv approved these changes
👍

2019-03-26 00:04 UTC, sarahmolinerroy commented
Thanks for the great feedback & suggestions 😃

2019-03-26 00:04 UTC, merged